# NORMALIZACION DE OUTLIERS Y QUIEBRES DE STOCK

**Autor: Abdias Figueredo V.**

**Version: 1.0**

**Agosto 2025**

**Cochabamba, Bolivia**

## Índice
1.  **Introducción**

2.  **Configuración Inicial**

3.  **Analisis Univariado**

4.  **Análisis de Distribuciones**

5.  **Análisis de Outliers**

7.  **Conclusiones**

## 1. INTRODUCCIÓN

Este proyecto tiene como objetivo realizar un Análisis Exploratorio de Datos (EDA) exhaustivo de los datos de ventas, productos e inventario de una empresa importadora de autopartes. La empresa maneja alrededor de 10,000 SKUs diferentes y tiene registros desde 2018 hasta la fecha actual, generados con IA simulando un sistema SAP Business One.

**Objetivos del EDA:**

*   Comprender la estructura y calidad de los datos disponibles.
*   Identificar patrones y tendencias en las ventas a lo largo del tiempo.
*   Analizar el comportamiento de los diferentes SKUs en términos de ventas y rotación de inventario.
*   Detectar posibles problemas en los datos, como valores atípicos o inconsistencias.
*   Generar hipótesis para futuros análisis y modelado predictivo.

**Tablas de Datos:**

*   **OITM (Tabla de Productos):** Contiene información detallada sobre cada producto, incluyendo su código, descripción, precio, etc.
*   **INV1 (Tabla de Ventas):** Registra las transacciones de venta, incluyendo la fecha, el SKU vendido, la cantidad, el precio, etc.
*   **OINM (Tabla de Inventario):** Contiene información sobre los movimientos de inventario, como entradas, salidas y ajustes.

---

## 2. CONFIGURACION INICIAL

### 2.1 Importación de librerías necesarias

In [1]:
# INSTALACION DE REQUIREMENTS
# Comando alternativo: pip install -r requirements.txt
#!pip install -r requirements.txt --quiet
# pip install --only-binary :all: statsforecast

In [2]:
# =============================================================================
# IMPORTACIÓN DE LIBRERÍAS
# =============================================================================
# Manejo y procesamiento de datos
# -----------------------------------------------------------------------------
import numpy as np
import pandas as pd
import os
import scipy.stats as stats
from pandas.tseries.offsets import DateOffset

# Análisis de series temporales
# -----------------------------------------------------------------------------
from statsforecast import StatsForecast
from utilsforecast.plotting import plot_series
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Visualización
# -----------------------------------------------------------------------------
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

# Configuración de advertencias
# -----------------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

# Configuración de estilos de visualización
# =============================================================================
# Configuración general de matplotlib
plt.style.use('classic')
plt.rcParams.update({
    'figure.figsize': (18, 7),
    'axes.facecolor': '#FFFFFF',  # Fondo blanco para mejor legibilidad
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.titlesize': 16
})

# Configuración de seaborn
#sns.set_theme(style="whitegrid", 
#              rc={'axes.facecolor': '#FFFFFF'},
#              font_scale=1.1)

c:\Users\abdia\AppData\Local\Programs\Python\Python313\Lib\site-packages\fs\__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__("pkg_resources").declare_namespace(__name__)  # type: ignore
c:\Users\abdia\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### 2.2 Carga de datos

In [3]:
# CARGA DE DATOS INV1
dataSales = pd.read_parquet('../data/bronze/inv1.parquet')
dfSales = dataSales.copy()

In [4]:
# CARGA DE DATOS OITM
dataItems = pd.read_parquet('../data/bronze/oitm.parquet')
dfItems = dataItems.copy()

In [ ]:
# CARGA DE DATOS dfWeekStock
dataWeekStock = pd.read_parquet('../data/silver/dfWeekStock.parquet')
dfWeekStock = dataWeekStock.copy()

In [46]:
# CARGA DE DATOS dfABC
dataABC = pd.read_parquet('../data/silver/dfABC.parquet')
dfABC = dataABC.copy()

---

### 2.3 Limpieza inicial

#### 2.3.1 Filtrado de Items

In [6]:
# INNER JOIN ENTRE OINM Y OITM PARA FILTRAR ITEMS INACTIVOS Y GRUPOS
dfSales = dfSales.merge(dfItems[['ItemCode', 'ItemGrp', 'FrozenFor']], 
                        on='ItemCode', 
                        how='inner')

In [7]:
# FILTRAR PARA QUITAR ITEMS INACTIVOS Y GRUPOS
def filter_active_items(df):
    """
    Filtra el DataFrame para eliminar items inactivos y grupos.
    
    Parámetros:
    -----------
    df : pandas.DataFrame
        DataFrame con columnas 'FrozenFor' y 'ItemGrp'
        
    Retorna:
    --------
    pandas.DataFrame
        DataFrame filtrado sin items inactivos ni grupos
    """
    # Filtrar items activos (no congelados) y grupos (no vacíos)
    filtered_df = df[(df['FrozenFor'] == 'N') & (df['ItemGrp'] != 124)]
    
    # Verificar si se eliminaron filas
    if len(filtered_df) < len(df):
        print(f"⚠️ Se eliminaron {len(df) - len(filtered_df):,} filas de items inactivos o grupos vacíos")
    
    return filtered_df

In [8]:
# USO DE LA FUNCION
dfSales = filter_active_items(dfSales)

⚠️ Se eliminaron 76,145 filas de items inactivos o grupos vacíos

In [9]:
# MOSTRAR LOS GRUPOS UNICOS
print("📋 ItemGrp únicos:"
      , dfSales['ItemGrp'].unique())

📋 ItemGrp únicos: [708 101 202 303 405 506 809 607]

#### 2.3.2 Agrupacion por semana

In [18]:
# FUNCION PARA PROCESAR VENTAS SEMANALES

def process_weekly_sales(df):
    """
    Procesa las ventas diarias en un resumen semanal usando isocalendar para semanas ISO 8601,
    considerando solo semanas completas.
    
    Parámetros:
    -----------
    df : pandas.DataFrame
        DataFrame con movimientos diarios de ventas que debe contener las columnas:
        ItemCode, DocDate, Quantity
    
    Retorna:
    --------
    pandas.DataFrame
        Resumen semanal de ventas con las columnas:
        ItemCode, StartWeek, Week, Quantity
    """
    # 1. Preparación de fechas con isocalendar
    df['DocDate'] = pd.to_datetime(df['DocDate'])
    df['IsoYear'] = df['DocDate'].dt.isocalendar().year
    df['IsoWeek'] = df['DocDate'].dt.isocalendar().week
    df['Week'] = df['IsoYear'].astype(str) + '-W' + df['IsoWeek'].astype(str).str.zfill(2)
    df['StartWeek'] = df['DocDate'] - pd.to_timedelta(df['DocDate'].dt.isocalendar().day - 1, unit='D')
    
    # 2. Identificar la última semana completa
    max_date = df['DocDate'].max()
    days_to_end_of_week = 7 - max_date.isocalendar().weekday
    
    if days_to_end_of_week < 7:
        # Usar isocalendar para la última semana completa
        last_complete_date = max_date - pd.Timedelta(days=7)
        last_complete_year = last_complete_date.isocalendar().year
        last_complete_week = last_complete_date.isocalendar().week
        last_complete_week_str = f"{last_complete_year}-W{str(last_complete_week).zfill(2)}"
        df = df[df['Week'] <= last_complete_week_str]
        print(f"⚠️ Se excluyó la semana incompleta: {max_date.isocalendar().year}-W{str(max_date.isocalendar().week).zfill(2)}")
    
    # 3. Agrupar por ítem y semana
    weekly = (df.groupby(['ItemCode', 'Week', 'StartWeek'])
             .agg({
                 'Quantity': 'sum',
                 'LineTotal': 'sum'  # Asegurarse de que LineTotal esté presente
             })
             .reset_index())
    
    # 4. Crear todas las combinaciones de semanas completas
    start_date = weekly['StartWeek'].min()
    end_date = weekly['StartWeek'].max()
    all_weeks = pd.date_range(start=start_date, 
                            end=end_date, 
                            freq='W-MON')
    
    items = weekly['ItemCode'].unique()
    
    # 5. Producto cartesiano de items y semanas
    complete_df = pd.DataFrame(
        [(item, week) for item in items for week in all_weeks],
        columns=['ItemCode', 'StartWeek']
    )
    
    # 6. Añadir formato de semana ISO usando isocalendar
    complete_df['IsoYear'] = complete_df['StartWeek'].dt.isocalendar().year
    complete_df['IsoWeek'] = complete_df['StartWeek'].dt.isocalendar().week
    complete_df['Week'] = complete_df['IsoYear'].astype(str) + '-W' + complete_df['IsoWeek'].astype(str).str.zfill(2)
    
    # 7. Unión con datos existentes
    weekly = pd.merge(
        complete_df,
        weekly[['ItemCode', 'Week', 'Quantity', 'LineTotal']],
        on=['ItemCode', 'Week'],
        how='left'
    )
    
    # 8. Rellenar valores faltantes
    weekly['Quantity'] = weekly['Quantity'].fillna(0)
    weekly['LineTotal'] = weekly['LineTotal'].fillna(0)
    
    # 9. Ordenar y seleccionar columnas finales
    result = weekly[['ItemCode', 'StartWeek', 'Week', 'Quantity', 'LineTotal']]
    
    return result.sort_values(['ItemCode', 'StartWeek'])

In [19]:
# Ejemplo de uso
dfWeekSales = process_weekly_sales(dfSales)
print("Muestra del resumen semanal de ventas:")
display(dfWeekSales.head(10))

⚠️ Se excluyó la semana incompleta: 2025-W32
Muestra del resumen semanal de ventas:

    ItemCode  StartWeek      Week  Quantity  LineTotal
0  SKU-00750 2018-01-01  2018-W01       0.0       0.00
1  SKU-00750 2018-01-08  2018-W02       0.0       0.00
2  SKU-00750 2018-01-15  2018-W03       7.0    2577.89
3  SKU-00750 2018-01-22  2018-W04       0.0       0.00
4  SKU-00750 2018-01-29  2018-W05       0.0       0.00
5  SKU-00750 2018-02-05  2018-W06       0.0       0.00
6  SKU-00750 2018-02-12  2018-W07       0.0       0.00
7  SKU-00750 2018-02-19  2018-W08       0.0       0.00
8  SKU-00750 2018-02-26  2018-W09       0.0       0.00
9  SKU-00750 2018-03-05  2018-W10       0.0       0.00

## 3. NORMALIZACION DE OUTLIERS

In [20]:
def normalize_outliers_by_item(df):
    """
    Detecta y normaliza outliers usando el método IQR por cada item,
    reemplazándolos por la mediana de valores no cero.
    
    Parámetros:
    -----------
    df : pandas.DataFrame
        DataFrame con las columnas ItemCode, StartWeek, Week, Quantity
    
    Retorna:
    --------
    pandas.DataFrame
        DataFrame con outliers normalizados y las mismas columnas de entrada
    """
    def replace_outliers(group):
        # Calcular IQR solo con valores no cero
        non_zero_values = group['Quantity'][group['Quantity'] > 0]
        if len(non_zero_values) == 0:
            return group
            
        Q1 = non_zero_values.quantile(0.25)
        Q3 = non_zero_values.quantile(0.75)
        IQR = Q3 - Q1
        
        # Definir límites
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # Identificar outliers
        outliers = (group['Quantity'] > upper_bound) | (group['Quantity'] < lower_bound)
        outliers = outliers & (group['Quantity'] > 0)  # Solo considerar valores no cero
        
        if outliers.any():
            # Calcular mediana de valores no cero
            median_non_zero = non_zero_values.median()
            
            # Reemplazar outliers con la mediana
            group.loc[outliers, 'Quantity'] = median_non_zero
            
            # Imprimir información de outliers encontrados
            n_outliers = outliers.sum()
            if n_outliers > 0:
                print(f"⚠️ Item {group['ItemCode'].iloc[0]}: {n_outliers} outliers reemplazados con mediana = {median_non_zero:.2f}")
        
        return group

    # Procesar cada item
    df_normalized = df.groupby('ItemCode', group_keys=False).apply(replace_outliers)
    
    return df_normalized[['ItemCode', 'StartWeek', 'Week', 'Quantity']].sort_values(['ItemCode', 'StartWeek'])

In [21]:
# Normalizar outliers
dfWeekSalesOutliers = normalize_outliers_by_item(dfWeekSales)

# Mostrar algunos ejemplos
print("\nMuestra del resultado:")
display(dfWeekSalesOutliers.head(10))

⚠️ Item SKU-00750: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00751: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00752: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00754: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00756: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00760: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00761: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00764: 10 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00765: 2 outliers reemplazados con mediana = 7.50
⚠️ Item SKU-00766: 9 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00767: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00769: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00771: 1 outliers reemplazados con mediana = 9.00
⚠️ Item SKU-00773: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00776: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00777: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00779: 11 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00781: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00782: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00783: 7 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00784: 6 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00787: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00792: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00793: 1 outliers reemplazados con mediana = 5.00
⚠️ Item SKU-00795: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00796: 9 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00797: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00799: 3 outliers reemplazados con mediana = 5.50
⚠️ Item SKU-00800: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00801: 11 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00803: 13 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00806: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00807: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00809: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00810: 6 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00812: 8 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00813: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00814: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00815: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00816: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00817: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00818: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00822: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00823: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00824: 5 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00825: 2 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00826: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00827: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00829: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00831: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00833: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00836: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00839: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00843: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00844: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00845: 7 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00846: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00847: 5 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00848: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00849: 5 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00851: 1 outliers reemplazados con mediana = 9.00
⚠️ Item SKU-00852: 3 outliers reemplazados con mediana = 7.50
⚠️ Item SKU-00853: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00854: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00855: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00859: 5 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00860: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00865: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00866: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00867: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00868: 7 outliers reemplazados con mediana = 6.50
⚠️ Item SKU-00869: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00870: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00872: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00874: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00875: 4 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00876: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00877: 4 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00878: 9 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00879: 11 outliers reemplazados con mediana = 6.50
⚠️ Item SKU-00881: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00884: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00885: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00887: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00889: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00890: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00892: 5 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00893: 17 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00894: 9 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00896: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00898: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00899: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00902: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00903: 9 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00905: 12 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00906: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00907: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00909: 9 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00910: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00911: 5 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00912: 7 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00913: 15 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00914: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00919: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00920: 4 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00924: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00925: 7 outliers reemplazados con mediana = 6.50
⚠️ Item SKU-00926: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00927: 6 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00928: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00929: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00930: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00931: 11 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00932: 11 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00934: 9 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00935: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00936: 6 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00937: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00938: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00939: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00940: 1 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00942: 8 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00944: 13 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00945: 15 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00946: 4 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00948: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00951: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00953: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00954: 5 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00955: 10 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00957: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00958: 8 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00959: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00960: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00961: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00963: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00964: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00966: 8 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00968: 4 outliers reemplazados con mediana = 9.00
⚠️ Item SKU-00972: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00973: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00974: 9 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00976: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00977: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00981: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00982: 7 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00983: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00986: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00987: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00989: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00990: 9 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00992: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00993: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-00996: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00997: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-00998: 5 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-00999: 4 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01002: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01003: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01005: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01006: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01007: 4 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01008: 9 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01011: 11 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01012: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01013: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01014: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01016: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01017: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01019: 9 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01023: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01024: 12 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01027: 8 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01030: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01031: 7 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01032: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01033: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01034: 6 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01042: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01043: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01044: 4 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01045: 13 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01047: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01048: 11 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01050: 8 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01051: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01052: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01053: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01054: 11 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01055: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01056: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01057: 2 outliers reemplazados con mediana = 7.50
⚠️ Item SKU-01058: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01059: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01060: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01061: 3 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01062: 6 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01063: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01067: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01069: 19 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01072: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01073: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01074: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01075: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01078: 8 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01079: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01081: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01082: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01084: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01085: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01086: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01087: 7 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01088: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01090: 11 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01091: 8 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01092: 10 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01093: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01094: 18 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01097: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01098: 7 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01099: 7 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01100: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01101: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01102: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01103: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01104: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01105: 6 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01106: 6 outliers reemplazados con mediana = 9.00
⚠️ Item SKU-01107: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01108: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01110: 5 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01111: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01112: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01113: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01114: 9 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01115: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01118: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01119: 5 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01120: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01122: 11 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01123: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01125: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01126: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01127: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01128: 2 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01129: 9 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01132: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01133: 6 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01134: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01135: 1 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01136: 2 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01137: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01138: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01140: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01143: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01144: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01145: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01146: 1 outliers reemplazados con mediana = 9.00
⚠️ Item SKU-01147: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01149: 5 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01152: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01153: 7 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01159: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01160: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01161: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01162: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01163: 5 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01164: 5 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01166: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01167: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01168: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01169: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01173: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01175: 9 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01177: 11 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01178: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01179: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01180: 3 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01181: 5 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01183: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01184: 2 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01187: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01189: 9 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01190: 13 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01191: 7 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01192: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01193: 4 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01195: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01197: 12 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01198: 10 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01199: 10 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01200: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01202: 7 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01203: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01204: 2 outliers reemplazados con mediana = 7.50
⚠️ Item SKU-01206: 13 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01208: 11 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01210: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01212: 6 outliers reemplazados con mediana = 7.50
⚠️ Item SKU-01214: 13 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01215: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01216: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01218: 8 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01219: 18 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01220: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01223: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01224: 3 outliers reemplazados con mediana = 7.50
⚠️ Item SKU-01226: 2 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01227: 4 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01228: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01229: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01231: 4 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01233: 3 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01234: 5 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01235: 8 outliers reemplazados con mediana = 6.00
⚠️ Item SKU-01236: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01238: 1 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01239: 11 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01240: 6 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01241: 7 outliers reemplazados con mediana = 7.00
⚠️ Item SKU-01242: 1 outliers reemplazados con mediana = 8.00
⚠️ Item SKU-01243: 3 outliers reemplazados con mediana = 8.00

    ItemCode  StartWeek      Week  Quantity
0  SKU-00750 2018-01-01  2018-W01       0.0
1  SKU-00750 2018-01-08  2018-W02       0.0
2  SKU-00750 2018-01-15  2018-W03       7.0
3  SKU-00750 2018-01-22  2018-W04       0.0
4  SKU-00750 2018-01-29  2018-W05       0.0
5  SKU-00750 2018-02-05  2018-W06       0.0
6  SKU-00750 2018-02-12  2018-W07       0.0
7  SKU-00750 2018-02-19  2018-W08       0.0
8  SKU-00750 2018-02-26  2018-W09       0.0
9  SKU-00750 2018-03-05  2018-W10       0.0

## 4. NORMALIZACION DE STOCKOUT

In [32]:
def normalize_stockout_demand(df_sales, df_stock):
    """
    Normaliza la demanda cuando hay stockout (sin ventas y sin stock disponible)
    usando la mediana de ventas no cero por item.
    
    Parámetros:
    -----------
    df_sales : pandas.DataFrame
        DataFrame con las columnas ItemCode, StartWeek, Week, Quantity 
    df_stock : pandas.DataFrame
        DataFrame con las columnas ItemCode, StartWeek, AvailableStock
        
    Retorna:
    --------
    pandas.DataFrame
        DataFrame con la demanda normalizada y columnas adicionales
    """
    # 1. Crear copia del dataframe original
    result = df_sales.copy()
    
    # 2. Merge con datos de stock
    result = result.merge(
        df_stock[['ItemCode', 'StartWeek', 'AvailableStock']], 
        on=['ItemCode', 'StartWeek'], 
        how='left'
    )
    
    # 3. Identificar condición de stockout 
    result['DemandStockout'] = ((result['Quantity'] == 0) & 
                            (result['AvailableStock'] <= 0)).astype(int)
    
    # 4. Normalizar por item usando la mediana de ventas no cero
    def normalize_item(group):
        # Calcular mediana de ventas no cero
        median_sales = group['Quantity'][group['Quantity'] > 0].median()
        
        # Si no hay ventas positivas, usar 0
        if pd.isna(median_sales):
            median_sales = 0
            
        # Crear columna normalizada
        group['Quantity'] = group['Quantity'].copy()
        
        # Reemplazar valores donde DemandStock = 1
        mask = group['DemandStockout'] == 1
        group.loc[mask, 'Quantity'] = median_sales
        
        # Contar normalizaciones
        n_normalized = mask.sum()
        if n_normalized > 0:
            print(f"⚠️ Item {group['ItemCode'].iloc[0]}: {n_normalized} semanas normalizadas con mediana = {median_sales:.2f}")
            
        return group
    
    # 5. Aplicar normalización por item
    result = result.groupby('ItemCode', group_keys=False).apply(normalize_item)
    
    # 6. Ordenar y seleccionar columnas finales
    columns = ['ItemCode', 'StartWeek', 'Week', 'Quantity', 
              'AvailableStock', 'DemandStockout']
    
    return result[columns].sort_values(['ItemCode', 'StartWeek'])

In [33]:
# Normalizar demanda por stockout
dfWeekSalesStockout = normalize_stockout_demand(dfWeekSalesOutliers, dfWeekStock)

# Mostrar resultados
print("\nMuestra del resultado:")
display(dfWeekSalesStockout.head(10))

⚠️ Item SKU-00750: 8 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00752: 121 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00756: 42 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00760: 8 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00764: 4 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00765: 4 semanas normalizadas con mediana = 7.25
⚠️ Item SKU-00766: 4 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00769: 44 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00771: 14 semanas normalizadas con mediana = 9.00
⚠️ Item SKU-00773: 21 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00776: 32 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00777: 22 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00779: 4 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00782: 26 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00783: 1 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00784: 2 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00792: 83 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00793: 88 semanas normalizadas con mediana = 5.00
⚠️ Item SKU-00795: 3 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00796: 8 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00797: 5 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00799: 21 semanas normalizadas con mediana = 5.25
⚠️ Item SKU-00800: 15 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00801: 1 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00803: 3 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00806: 29 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00809: 12 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00810: 11 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00812: 3 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00813: 57 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00814: 4 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00815: 11 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00816: 14 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00817: 8 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00818: 16 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00822: 86 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00824: 6 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00825: 45 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00826: 4 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00827: 6 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00833: 61 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00842: 77 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00844: 31 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00845: 2 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00846: 11 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00847: 11 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00848: 28 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00849: 124 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00851: 245 semanas normalizadas con mediana = 9.00
⚠️ Item SKU-00852: 20 semanas normalizadas con mediana = 7.25
⚠️ Item SKU-00853: 6 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00854: 1 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00855: 68 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00860: 14 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00865: 99 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00866: 1 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00867: 3 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00868: 12 semanas normalizadas con mediana = 6.25
⚠️ Item SKU-00869: 16 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00870: 72 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00871: 6 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00872: 43 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00874: 5 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00875: 74 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00876: 11 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00877: 38 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00878: 9 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00879: 4 semanas normalizadas con mediana = 6.25
⚠️ Item SKU-00881: 2 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00884: 6 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00885: 51 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00887: 7 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00889: 47 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00892: 29 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00893: 76 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00894: 5 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00895: 39 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00896: 34 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00898: 28 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00899: 61 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00902: 20 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00903: 12 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00905: 6 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00906: 118 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00907: 40 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00909: 104 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00910: 23 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00911: 43 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00912: 12 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00913: 1 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00914: 44 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00919: 3 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00920: 53 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00921: 92 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00922: 79 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00924: 28 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00925: 8 semanas normalizadas con mediana = 6.25
⚠️ Item SKU-00927: 31 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00928: 4 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00929: 66 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00930: 7 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00931: 124 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00932: 61 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00934: 14 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00936: 4 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00938: 57 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00939: 35 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00940: 66 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00942: 5 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00944: 5 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00945: 6 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00946: 8 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00948: 22 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00951: 68 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00953: 1 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00954: 3 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00955: 8 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00957: 43 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00958: 123 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00960: 6 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00961: 8 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00963: 66 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00966: 93 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00968: 14 semanas normalizadas con mediana = 9.00
⚠️ Item SKU-00973: 8 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00974: 3 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00976: 18 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00981: 49 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00982: 8 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00983: 38 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00984: 83 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00986: 51 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00987: 83 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00989: 6 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00990: 11 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00993: 43 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-00996: 40 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00997: 165 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-00998: 4 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-00999: 14 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01002: 49 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01003: 87 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01005: 51 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01006: 3 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01007: 13 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01008: 8 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01009: 2 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01011: 41 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01012: 45 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01013: 20 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01014: 70 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01015: 31 semanas normalizadas con mediana = 9.00
⚠️ Item SKU-01016: 47 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01017: 41 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01019: 80 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01024: 73 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01027: 7 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01030: 46 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01031: 43 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01032: 6 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01033: 2 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01034: 113 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01038: 4 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01043: 86 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01044: 82 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01045: 4 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01047: 52 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01048: 13 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01050: 14 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01052: 38 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01053: 5 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01054: 10 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01055: 9 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01056: 6 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01057: 57 semanas normalizadas con mediana = 7.25
⚠️ Item SKU-01058: 37 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01059: 102 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01061: 2 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01062: 61 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01063: 6 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01069: 4 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01070: 84 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01071: 79 semanas normalizadas con mediana = 30.00
⚠️ Item SKU-01073: 75 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01074: 13 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01078: 6 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01079: 3 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01081: 29 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01082: 10 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01084: 104 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01086: 27 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01087: 9 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01088: 17 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01090: 63 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01091: 13 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01092: 167 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01093: 6 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01094: 14 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01098: 4 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01099: 4 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01100: 32 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01101: 81 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01102: 89 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01103: 42 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01105: 3 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01106: 79 semanas normalizadas con mediana = 9.00
⚠️ Item SKU-01107: 14 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01108: 22 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01110: 7 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01112: 12 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01113: 15 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01114: 3 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01115: 32 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01116: 71 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01118: 8 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01120: 4 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01122: 64 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01125: 15 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01126: 9 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01127: 10 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01128: 13 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01129: 7 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01132: 54 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01133: 52 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01134: 23 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01135: 52 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01136: 8 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01137: 6 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01138: 10 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01140: 9 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01143: 8 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01144: 36 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01145: 15 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01146: 128 semanas normalizadas con mediana = 9.00
⚠️ Item SKU-01149: 12 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01153: 3 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01159: 52 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01163: 35 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01164: 14 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01166: 5 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01167: 4 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01168: 12 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01169: 10 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01173: 5 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01175: 10 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01177: 37 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01178: 13 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01179: 7 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01183: 4 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01184: 46 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01187: 5 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01189: 3 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01190: 35 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01191: 3 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01192: 11 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01193: 10 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01197: 68 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01198: 4 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01199: 4 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01202: 14 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01203: 15 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01206: 3 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01208: 9 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01210: 2 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01212: 5 semanas normalizadas con mediana = 7.50
⚠️ Item SKU-01214: 3 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01215: 76 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01216: 3 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01217: 7 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01218: 7 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01219: 7 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01220: 53 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01222: 31 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01223: 14 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01224: 3 semanas normalizadas con mediana = 7.25
⚠️ Item SKU-01226: 32 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01229: 12 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01231: 4 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01233: 15 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01234: 6 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01235: 7 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01236: 12 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01237: 42 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01239: 56 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01240: 11 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01241: 13 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01242: 79 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01243: 5 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01244: 64 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01247: 71 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01251: 12 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01253: 11 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01257: 20 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01258: 15 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01260: 110 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01261: 12 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01262: 10 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01265: 103 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01267: 7 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01269: 5 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01272: 54 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01278: 2 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01279: 14 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01280: 71 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01282: 36 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01285: 34 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01286: 47 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01287: 2 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01288: 24 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01289: 20 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01291: 46 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01292: 42 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01293: 59 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01295: 37 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01298: 5 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01300: 15 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01301: 10 semanas normalizadas con mediana = 6.00
⚠️ Item SKU-01302: 5 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01303: 55 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01306: 9 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01309: 57 semanas normalizadas con mediana = 8.00
⚠️ Item SKU-01310: 16 semanas normalizadas con mediana = 7.00
⚠️ Item SKU-01311: 107 semanas normalizadas con mediana = 7.50
⚠️ Item SKU-01312: 30 semanas normalizadas con mediana = 7.00

    ItemCode  StartWeek      Week  Quantity  AvailableStock  DemandStockout
0  SKU-00750 2018-01-01  2018-W01       0.0           102.0               0
1  SKU-00750 2018-01-08  2018-W02       0.0           102.0               0
2  SKU-00750 2018-01-15  2018-W03       7.0            95.0               0
3  SKU-00750 2018-01-22  2018-W04       0.0            95.0               0
4  SKU-00750 2018-01-29  2018-W05       0.0            95.0               0
5  SKU-00750 2018-02-05  2018-W06       0.0            95.0               0
6  SKU-00750 2018-02-12  2018-W07       0.0            95.0               0
7  SKU-00750 2018-02-19  2018-W08       0.0            95.0               0
8  SKU-00750 2018-02-26  2018-W09       0.0            95.0               0
9  SKU-00750 2018-03-05  2018-W10       0.0            95.0               0

## 6. AJUSTES PARA EXPORTAR DATAFRAME

### 6.1 FACT VENTAS SEMANALES

In [49]:
# MERGE DE DATAFRAMES DFWEEKSALES Y DFWEEKSALESSTOCKOUT
FactWeekSales = pd.merge(
    dfWeekSales[['ItemCode', 'StartWeek','Week','Quantity', 'LineTotal']],
    dfWeekSalesStockout[['ItemCode','StartWeek','Week','Quantity','AvailableStock', 'DemandStockout']],
    on=['ItemCode', 'StartWeek', 'Week'],
    how='left'
)

In [50]:
# RENOMBRAR COLUMNAS QUANTITY
FactWeekSales = FactWeekSales.rename(columns={
    'Quantity_y': 'NormalizedQuantity',
    'Quantity_x': 'OriginalQuantity'
})

In [51]:
# AÑADIR COLUMNA PRECIO UNITARIO
FactWeekSales['Price'] = FactWeekSales['LineTotal'] / FactWeekSales['OriginalQuantity']

# RELLENAR LOS VALORES NULOS DEL PRICE CON LOS VALORES PROXIMOS
# Rellenar valores nulos por ItemCode usando forward fill y backward fill
FactWeekSales['Price'] = FactWeekSales.groupby('ItemCode')['Price'].transform(
    lambda x: x.fillna(method='ffill').fillna(method='bfill')
)

# Verificar si quedaron nulos
nulos = FactWeekSales['Price'].isnull().sum()
if nulos > 0:
    print(f"⚠️ Quedaron {nulos} valores nulos en Price")

In [52]:
# ORDENAR COLUMNAS
FactWeekSales = FactWeekSales[['ItemCode', 'StartWeek', 'Week', 
                                       'OriginalQuantity','NormalizedQuantity','Price','LineTotal', 
                                       'AvailableStock', 'DemandStockout']]

## 7. GUARDADO DE DATAFRAME

In [53]:
# GUARDAR EL DATAFRAME PROCESADO DFStock
FactWeekSales.to_parquet('../data/gold/FactWeekSales.parquet', index=False)

## 6. CONCLUSIONES

- Se identificaron que los productos mas vendidos son los SKUs 06074, 03543 y 03063.
- El análisis de distribución mostró que las ventas semanales no siguen una distribución normal (p-valor < 0.05 en la prueba de Shapiro-Wilk), lo que es común en datos de ventas del mundo real debido a factores externos como promociones o eventos estacionales.
- El analisis de outliers mostro que hay 2 valoes atipicos en la variable ventas semanales. Es coveniente normalizar estos datos ya que el proximo paso sera crear un modelo de pronostico.